// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hofzwvtumizrnmsnysbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZnp3dnR1bWl6cm5tc255c2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTEwMDYsImV4cCI6MjA3MTM4NzAwNn0.tmYp9Gv25kMGhjnTSjKOcZR30NmYaO0tkZugVXcvYL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});